codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: 0
    patch:
      default:
        target: 0
        threshold: 0

ignore:
  - 'nimare/tests/'
  - 'nimare/due.py'
  - 'nimare/_version.py'
  - 'nimare/info.py'
  - 'nimare/references.py'
