codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: null
    patch:
      default:
        target: 0
        threshold: null
  ignore:
    - 'nimare/tests/'
    - 'nimare/due.py'
    - 'nimare/_version.py'
    - 'nimare/info.py'
    - 'nimare/references.py'
