name: nimare_env

channels:
  - conda-forge

dependencies:
  - python=3.8
  - cognitiveatlas
  - fuzzywuzzy
  - indexed_gzip>=1.4.0
  - joblib
  - matplotlib>=3.3
  - nibabel>=3.0.0
  - nilearn>=0.9.2
  - numba
  - numpy<1.24,>=1.18
  - pandas>=1.1.0
  - pymare~=0.0.4rc2
  - requests
  - scikit-learn
  - scipy
  - sparse>=0.13.0
  - statsmodels!=0.13.2
  - tqdm
  - m2r
  - matplotlib
  - mistune<2
  - pillow
  - recommonmark
  - seaborn
  - sphinx>=3.5
  - sphinx-argparse
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - jupyterlite-sphinx
  - jupyterlite-pyodide-kernel

