name: nimare_env

channels:
  - conda-forge

dependencies:
  - python=3.8
  - m2r
  - matplotlib
  - mistune<2
  - pillow
  - recommonmark
  - seaborn
  - sphinx>=3.5
  - sphinx-argparse
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - pip
  - pip:
    - ..
    - jupyterlite-core
    - jupyterlite-sphinx
    - jupyterlite-pyodide-kernel

