name: nimare-lite
# this is a conda environment for building the JupyterLite documentation

channels:
  - conda-forge

dependencies:
  - nodejs >=18,<19
  - python=3.8
  # build
  cognitiveatlas  # nimare.annotate.cogat
  - fuzzywuzzy  # nimare.annotate
  - indexed_gzip>=1.4.0  # working with gzipped niftis
  - joblib  # parallelization
  - matplotlib>=3.3  # this is for nilearn, which doesn't include it in its reqs
  - nibabel>=3.0.0  # I/O of niftis
  - nilearn>=0.9.2
  - numba  # used by sparse
  - numpy<1.24,>=1.18 # for compatibility with numba https://github.com/numba/numba/issues/8615
  - pandas>=1.1.0
  - pymare~=0.0.4rc2  # nimare.meta.ibma and stats
  - requests  # nimare.extract
  - scikit-learn  # nimare.annotate and nimare.decode
  - scipy
  - sparse>=0.13.0  # for kernel transformers
  - statsmodels!=0.13.2  # this version doesn't install properly
  - tqdm  # progress bars throughout package
  # docs
  - m2r
  - matplotlib
  - mistune<2  # just temporary until m2r addresses this issue
  - pillow
  - recommonmark
  - seaborn
  - sphinx>=3.5
  - sphinx-argparse
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - pip:
    - jupyterlite-sphinx
    - jupyterlite-pyodide-kernel

