name: Build nimare WASM

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYODIDE_VERSION: 0.23.1
      # PYTHON_VERSION and EMSCRIPTEN_VERSION are determined by PYODIDE_VERSION.
      # The appropriate versions can be found in the Pyodide repodata.json
      # "info" field, or in Makefile.envs:
      # https://github.com/pyodide/pyodide/blob/main/Makefile.envs#L2
      PYTHON_VERSION: 3.10
      EMSCRIPTEN_VERSION: 3.1.32
      
    steps:
      - name: Checkout nimare
        uses: actions/checkout@v3
        
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}

      - name: Install pyodide-build
        run: pip install pyodide-build==$PYODIDE_VERSION

      - name: Build
        run: CFLAGS=-g2 LDFLAGS=-g2 pyodide build

      - name: Set up Pyodide virtual environment
        run: |
          pyodide venv .venv-pyodide
          source .venv-pyodide/bin/activate
          pip install dist/*.whl
          pip install -e .[tests,peaks2maps-cpu]
      
      - name: 'Run tests'
        run: |
          source .venv-pyodide/bin/activate
          cd ..
          make unittest