name: "Lint Code"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Determine if tests should be run based on commit message.
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.result_step.outputs.ci-skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: result_step
        uses: mstachniuk/ci-skip@master
        with:
          commit-filter: '[skip ci];[ci skip];[skip github]'
          commit-filter-separator: ';'

  style_check:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: "ubuntu-latest"
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-latest"]
            python-version: ["3.7"]
    name: Style check
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up python'
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: 'Install NiMARE'
        shell: bash {0}
        run: pip install -e .[tests]
      - name: 'Run linter'
        shell: bash {0}
        run: make lint
